/**
 * Story 2.1 — Spaces store.
 *
 * The directory `spaces/<family_id>/<category>/<slug>.md` is the
 * source of truth for compiled understanding, alongside the database.
 * Writes go to both: DB row first (atomic, transactional), then disk +
 * git commit. The DB row is the programmatic read path; the directory
 * is the human-auditable, git-versioned, Article-20-exportable form.
 *
 * Every write is committed to a local git repo rooted at
 * MEMU_SPACES_ROOT (default: ./data/spaces). This gives us free
 * version history and blame for synthesis updates without any
 * external services.
 */

import { promises as fs } from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import crypto from 'crypto';
import matter from 'gray-matter';
import { pool } from '../db/connection';
import {
  buildSpaceUri,
  slugify,
  type Space,
  type SpaceCategory,
  type SpaceDomain,
  type Visibility,
} from './model';

function spacesRoot(): string {
  return process.env.MEMU_SPACES_ROOT ?? path.resolve(process.cwd(), 'data', 'spaces');
}

function familyDir(familyId: string): string {
  return path.join(spacesRoot(), familyId);
}

function filePath(familyId: string, category: SpaceCategory, slug: string): string {
  return path.join(familyDir(familyId), `${category}s`, `${slug}.md`);
}

function logPath(familyId: string): string {
  return path.join(familyDir(familyId), '_log.md');
}

async function ensureFamilyRepo(familyId: string): Promise<void> {
  const dir = familyDir(familyId);
  await fs.mkdir(dir, { recursive: true });
  const gitDir = path.join(dir, '.git');
  let freshlyInitialised = false;
  try {
    await fs.access(gitDir);
  } catch {
    // Git is the version-history substrate for the Spaces directory but
    // the DB row + on-disk markdown are the source of truth. If git is
    // unavailable (binary missing, ENOENT, sandbox restrictions),
    // version history is degraded but Spaces still work — don't crash
    // the Space write. Same pattern as the inner add/commit below.
    try {
      execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: dir });
      execFileSync('git', ['config', 'user.email', 'memu@localhost'], { cwd: dir });
      execFileSync('git', ['config', 'user.name', 'Memu'], { cwd: dir });
      freshlyInitialised = true;
    } catch (err) {
      console.warn('[SPACES] git init non-fatal — Space history disabled:', (err as Error).message ?? err);
    }
  }
  await ensureReadme(familyId, freshlyInitialised);
}

async function resolveActor(actorProfileId: string | undefined): Promise<{ name: string; email: string }> {
  if (!actorProfileId) return { name: 'Memu', email: 'memu@localhost' };
  try {
    const res = await pool.query<{ display_name: string; email: string | null }>(
      `SELECT display_name, email FROM profiles WHERE id = $1 LIMIT 1`,
      [actorProfileId],
    );
    const row = res.rows[0];
    if (!row) return { name: 'Memu', email: 'memu@localhost' };
    return {
      name: row.display_name || 'Memu',
      email: row.email ?? `${actorProfileId}@memu.local`,
    };
  } catch {
    return { name: 'Memu', email: 'memu@localhost' };
  }
}

const README_BODY = `# Memu Spaces

This directory is the source of truth for **compiled understanding** about your family — the persistent, curated pages Memu maintains alongside its database.

## Structure

\`\`\`
spaces/<family_id>/
├── persons/        # one .md per person
├── routines/       # one .md per routine
├── households/     # household-level concerns (the car, the garden)
├── commitments/    # ongoing or upcoming commitments
├── documents/      # extracted documents (MOTs, passports, letters)
├── _log.md         # append-only audit log of every write
└── README.md       # this file
\`\`\`

Every .md file has YAML frontmatter (id, name, category, domains, people,
visibility, description, confidence, last_updated, source_references, tags)
and a markdown body. Wikilinks in the body — \`[[robin]]\`, \`[[school-run]]\` —
follow Obsidian conventions.

## How to read it

- **In Obsidian:** open this directory as a vault. Wikilinks form a graph view.
- **In a text editor:** every file is plain markdown.
- **In the mobile app:** the Spaces tab renders the database mirror.
- **In git:** \`git log\` shows the full history of synthesis updates,
  attributed to the person (or skill) that triggered each change.

## Backups & exports

This directory is git-versioned for free history. The complete archive
(including \`.git/\`) can be exported via \`POST /api/spaces/snapshot\` from
Settings, or as part of the full Article 20 export.

— Generated by Memu. Do not delete.
`;

async function ensureReadme(familyId: string, force = false): Promise<void> {
  const target = path.join(familyDir(familyId), 'README.md');
  if (!force) {
    try {
      await fs.access(target);
      return;
    } catch { /* fall through to write */ }
  }
  await fs.writeFile(target, README_BODY, 'utf8');
  try {
    execFileSync('git', ['add', '--', 'README.md'], { cwd: familyDir(familyId), stdio: 'ignore' });
    execFileSync(
      'git',
      ['commit', '-q', '-m', 'Initialise spaces directory', '--author', 'Memu <memu@localhost>'],
      { cwd: familyDir(familyId), stdio: 'ignore' },
    );
  } catch (err) {
    const msg = (err as Error).message ?? '';
    if (!/nothing to commit/i.test(msg)) {
      console.warn('[SPACES] README commit non-fatal:', msg);
    }
  }
}

export interface SpaceWriteInput {
  familyId: string;
  category: SpaceCategory;
  name: string;
  bodyMarkdown: string;
  description?: string;
  domains?: SpaceDomain[];
  people?: string[];
  visibility?: Visibility;
  confidence?: number;
  sourceReferences?: string[];
  tags?: string[];
  slug?: string;
  actorProfileId?: string;
}

/**
 * Upsert a Space, keyed on (family_id, category, slug). If a row
 * already exists at that key, this becomes an update (keeps the URI).
 * Otherwise a new row is minted with a freshly-generated URI.
 */
export async function upsertSpace(input: SpaceWriteInput): Promise<Space> {
  const slug = input.slug ?? slugify(input.name);
  const client = await pool.connect();
  let existingId: string | null = null;
  let existingUri: string | null = null;
  try {
    await client.query('BEGIN');
    const existing = await client.query<{ id: string; uri: string }>(
      `SELECT id, uri FROM synthesis_pages
        WHERE family_id = $1 AND category = $2 AND slug = $3
        LIMIT 1`,
      [input.familyId, input.category, slug],
    );
    if (existing.rows[0]) {
      existingId = existing.rows[0].id;
      existingUri = existing.rows[0].uri;
    }

    const id = existingId ?? crypto.randomUUID();
    const uri = existingUri ?? buildSpaceUri(input.familyId, input.category, id);
    const visibilityStored = Array.isArray(input.visibility)
      ? JSON.stringify(input.visibility)
      : (input.visibility ?? 'family');

    const profileId = input.actorProfileId ?? input.familyId;

    await client.query(
      `INSERT INTO synthesis_pages (
         id, profile_id, family_id, uri, slug, category, title, body_markdown,
         description, domains, people, visibility, confidence,
         source_references, tags, last_updated_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15, NOW())
       ON CONFLICT (id) DO UPDATE SET
         title = EXCLUDED.title,
         body_markdown = EXCLUDED.body_markdown,
         description = EXCLUDED.description,
         domains = EXCLUDED.domains,
         people = EXCLUDED.people,
         visibility = EXCLUDED.visibility,
         confidence = EXCLUDED.confidence,
         source_references = EXCLUDED.source_references,
         tags = EXCLUDED.tags,
         last_updated_at = NOW()`,
      [
        id,
        profileId,
        input.familyId,
        uri,
        slug,
        input.category,
        input.name,
        input.bodyMarkdown,
        input.description ?? '',
        input.domains ?? [],
        input.people ?? [],
        visibilityStored,
        input.confidence ?? 0.5,
        input.sourceReferences ?? [],
        input.tags ?? [],
      ],
    );

    await client.query(
      `INSERT INTO spaces_log (family_id, space_uri, event, summary, actor_profile_id)
       VALUES ($1, $2, $3, $4, $5)`,
      [
        input.familyId,
        uri,
        existingId ? 'updated' : 'created',
        `${existingId ? 'Updated' : 'Created'} ${input.category} "${input.name}"`,
        input.actorProfileId ?? null,
      ],
    );

    await client.query('COMMIT');

    const space: Space = {
      uri,
      id,
      familyId: input.familyId,
      category: input.category,
      slug,
      name: input.name,
      description: input.description ?? '',
      domains: input.domains ?? [],
      people: input.people ?? [],
      visibility: input.visibility ?? 'family',
      confidence: input.confidence ?? 0.5,
      sourceReferences: input.sourceReferences ?? [],
      tags: input.tags ?? [],
      bodyMarkdown: input.bodyMarkdown,
      lastUpdated: new Date(),
    };

    await writeToDisk(space, existingId ? 'updated' : 'created', input.actorProfileId);
    return space;
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

function renderFrontmatter(space: Space): string {
  const fm = {
    id: space.uri,
    name: space.name,
    category: space.category,
    domains: space.domains,
    people: space.people,
    visibility: space.visibility,
    description: space.description,
    confidence: space.confidence,
    last_updated: space.lastUpdated.toISOString(),
    source_references: space.sourceReferences,
    tags: space.tags,
  };
  return matter.stringify(space.bodyMarkdown.endsWith('\n') ? space.bodyMarkdown : `${space.bodyMarkdown}\n`, fm);
}

async function writeToDisk(space: Space, event: 'created' | 'updated', actorProfileId?: string): Promise<void> {
  await ensureFamilyRepo(space.familyId);
  const target = filePath(space.familyId, space.category, space.slug);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, renderFrontmatter(space), 'utf8');

  const logLine = `- ${space.lastUpdated.toISOString()} · ${event} · [[${space.slug}]] (${space.category})\n`;
  await fs.appendFile(logPath(space.familyId), logLine, 'utf8');

  const relFile = path.relative(familyDir(space.familyId), target);
  const relLog = path.relative(familyDir(space.familyId), logPath(space.familyId));
  const actor = await resolveActor(actorProfileId);
  const verb = event === 'created' ? 'Created' : 'Updated';
  const message = `${verb} ${space.category}/${space.slug}.md\n\n${space.name}\nVisibility: ${Array.isArray(space.visibility) ? 'explicit' : space.visibility}`;
  try {
    execFileSync('git', ['add', '--', relFile, relLog], { cwd: familyDir(space.familyId), stdio: 'ignore' });
    execFileSync(
      'git',
      ['commit', '-q', '-m', message, '--author', `${actor.name} <${actor.email}>`],
      { cwd: familyDir(space.familyId), stdio: 'ignore' },
    );
  } catch (err) {
    const msg = (err as Error).message ?? '';
    if (!/nothing to commit/i.test(msg)) {
      console.warn('[SPACES] git commit non-fatal:', msg);
    }
  }
}

interface SpaceRow {
  id: string;
  family_id: string;
  uri: string;
  slug: string;
  category: SpaceCategory;
  title: string;
  body_markdown: string;
  description: string;
  domains: string[];
  people: string[];
  visibility: string;
  confidence: string;
  source_references: string[];
  tags: string[];
  last_updated_at: Date;
}

function rowToSpace(row: SpaceRow): Space {
  let visibility: Visibility;
  if (row.visibility.startsWith('[')) {
    try {
      visibility = JSON.parse(row.visibility) as string[];
    } catch {
      visibility = 'family';
    }
  } else {
    visibility = row.visibility as Visibility;
  }
  return {
    uri: row.uri,
    id: row.id,
    familyId: row.family_id,
    category: row.category,
    slug: row.slug,
    name: row.title,
    description: row.description,
    domains: row.domains as SpaceDomain[],
    people: row.people,
    visibility,
    confidence: Number(row.confidence),
    sourceReferences: row.source_references,
    tags: row.tags,
    bodyMarkdown: row.body_markdown,
    lastUpdated: row.last_updated_at,
  };
}

export async function findSpaceByUri(uri: string): Promise<Space | null> {
  const res = await pool.query<SpaceRow>(
    `SELECT id, family_id, uri, slug, category, title, body_markdown,
            description, domains, people, visibility, confidence,
            source_references, tags, last_updated_at
       FROM synthesis_pages WHERE uri = $1`,
    [uri],
  );
  return res.rows[0] ? rowToSpace(res.rows[0]) : null;
}

export async function findSpaceBySlug(familyId: string, category: SpaceCategory, slug: string): Promise<Space | null> {
  const res = await pool.query<SpaceRow>(
    `SELECT id, family_id, uri, slug, category, title, body_markdown,
            description, domains, people, visibility, confidence,
            source_references, tags, last_updated_at
       FROM synthesis_pages
      WHERE family_id = $1 AND category = $2 AND slug = $3`,
    [familyId, category, slug],
  );
  return res.rows[0] ? rowToSpace(res.rows[0]) : null;
}

export async function listSpaces(familyId: string): Promise<Space[]> {
  const res = await pool.query<SpaceRow>(
    `SELECT id, family_id, uri, slug, category, title, body_markdown,
            description, domains, people, visibility, confidence,
            source_references, tags, last_updated_at
       FROM synthesis_pages WHERE family_id = $1
      ORDER BY last_updated_at DESC`,
    [familyId],
  );
  return res.rows.map(rowToSpace);
}

/**
 * Delete a Space. Removes the DB row, the on-disk markdown file, and
 * commits the deletion to the family's git repo so blame still shows
 * who removed it. Returns true if a row was deleted, false if the slug
 * was already gone (idempotent — callers don't need to pre-check).
 */
export async function deleteSpace(
  familyId: string,
  category: SpaceCategory,
  slug: string,
  actorProfileId?: string,
): Promise<boolean> {
  const client = await pool.connect();
  let removedUri: string | null = null;
  let removedTitle: string | null = null;
  try {
    await client.query('BEGIN');
    const existing = await client.query<{ uri: string; title: string }>(
      `SELECT uri, title FROM synthesis_pages
        WHERE family_id = $1 AND category = $2 AND slug = $3
        LIMIT 1`,
      [familyId, category, slug],
    );
    if (!existing.rows[0]) {
      await client.query('ROLLBACK');
      return false;
    }
    removedUri = existing.rows[0].uri;
    removedTitle = existing.rows[0].title;

    await client.query(
      `DELETE FROM synthesis_pages WHERE family_id = $1 AND category = $2 AND slug = $3`,
      [familyId, category, slug],
    );
    await client.query(
      `INSERT INTO spaces_log (family_id, space_uri, event, summary, actor_profile_id)
       VALUES ($1, $2, 'deleted', $3, $4)`,
      [familyId, removedUri, `Deleted ${category} "${removedTitle}"`, actorProfileId ?? null],
    );
    await client.query('COMMIT');
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    client.release();
  }

  // Best-effort filesystem cleanup. The DB is the source of truth; if
  // the file is missing the delete still succeeded.
  try {
    await ensureFamilyRepo(familyId);
    const target = filePath(familyId, category, slug);
    try { await fs.unlink(target); } catch { /* already gone */ }
    const logLine = `- ${new Date().toISOString()} · deleted · [[${slug}]] (${category})\n`;
    await fs.appendFile(logPath(familyId), logLine, 'utf8');
    const relFile = path.relative(familyDir(familyId), target);
    const relLog = path.relative(familyDir(familyId), logPath(familyId));
    const actor = await resolveActor(actorProfileId);
    try {
      execFileSync('git', ['add', '--', relFile, relLog], { cwd: familyDir(familyId), stdio: 'ignore' });
      execFileSync(
        'git',
        ['commit', '-q', '-m', `Deleted ${category}/${slug}.md`, '--author', `${actor.name} <${actor.email}>`],
        { cwd: familyDir(familyId), stdio: 'ignore' },
      );
    } catch (err) {
      const msg = (err as Error).message ?? '';
      if (!/nothing to commit/i.test(msg)) {
        console.warn('[SPACES] git delete commit non-fatal:', msg);
      }
    }
  } catch (err) {
    console.warn('[SPACES] filesystem cleanup non-fatal:', (err as Error).message);
  }

  return true;
}

/**
 * Re-derive the on-disk spaces tree from the database. Used after
 * migrations, disaster recovery, or manual surgery. Idempotent.
 */
export async function rebuildOnDisk(familyId: string): Promise<number> {
  const spaces = await listSpaces(familyId);
  await ensureFamilyRepo(familyId);
  for (const space of spaces) {
    await writeToDisk(space, 'updated', familyId);
  }
  return spaces.length;
}
