/**
 * Story 2.1 — Spaces store.
 *
 * The directory `spaces/<family_id>/<category>/<slug>.md` is the
 * source of truth for compiled understanding, alongside the database.
 * Writes go to both: DB row first (atomic, transactional), then disk +
 * git commit. The DB row is the programmatic read path; the directory
 * is the human-auditable, git-versioned, Article-20-exportable form.
 *
 * Every write is committed to a local git repo rooted at
 * MEMU_SPACES_ROOT (default: ./data/spaces). This gives us free
 * version history and blame for synthesis updates without any
 * external services.
 */

import { promises as fs } from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import crypto from 'crypto';
import matter from 'gray-matter';
import { db } from '../db/tenant';
import { embedText } from '../intelligence/context';
import { persistWikilinkEdges } from './wikilinks';
import { assignPassageIds } from './passageIds';
import {
  buildSpaceUri,
  isCategoryAllowedForType,
  slugify,
  type Space,
  type SpaceCategory,
  type SpaceDomain,
  type Visibility,
} from './model';

function spacesRoot(): string {
  return process.env.MEMU_SPACES_ROOT ?? path.resolve(process.cwd(), 'data', 'spaces');
}

function familyDir(familyId: string): string {
  return path.join(spacesRoot(), familyId);
}

function filePath(familyId: string, category: SpaceCategory, slug: string): string {
  return path.join(familyDir(familyId), `${category}s`, `${slug}.md`);
}

function logPath(familyId: string): string {
  return path.join(familyDir(familyId), '_log.md');
}

async function ensureFamilyRepo(familyId: string): Promise<void> {
  const dir = familyDir(familyId);
  await fs.mkdir(dir, { recursive: true });
  const gitDir = path.join(dir, '.git');
  let freshlyInitialised = false;
  try {
    await fs.access(gitDir);
  } catch {
    // Git is the version-history substrate for the Spaces directory but
    // the DB row + on-disk markdown are the source of truth. If git is
    // unavailable (binary missing, ENOENT, sandbox restrictions),
    // version history is degraded but Spaces still work — don't crash
    // the Space write. Same pattern as the inner add/commit below.
    try {
      execFileSync('git', ['init', '-q', '-b', 'main'], { cwd: dir });
      execFileSync('git', ['config', 'user.email', 'memu@localhost'], { cwd: dir });
      execFileSync('git', ['config', 'user.name', 'Memu'], { cwd: dir });
      freshlyInitialised = true;
    } catch (err) {
      console.warn('[SPACES] git init non-fatal — Space history disabled:', (err as Error).message ?? err);
    }
  }
  await ensureReadme(familyId, freshlyInitialised);
}

async function resolveActor(actorProfileId: string | undefined): Promise<{ name: string; email: string }> {
  if (!actorProfileId) return { name: 'Memu', email: 'memu@localhost' };
  try {
    const res = await db.query<{ display_name: string; email: string | null }>(
      `SELECT display_name, email FROM profiles WHERE id = $1 LIMIT 1`,
      [actorProfileId],
    );
    const row = res.rows[0];
    if (!row) return { name: 'Memu', email: 'memu@localhost' };
    return {
      name: row.display_name || 'Memu',
      email: row.email ?? `${actorProfileId}@memu.local`,
    };
  } catch {
    return { name: 'Memu', email: 'memu@localhost' };
  }
}

const README_BODY = `# Memu Spaces

This directory is the source of truth for **compiled understanding** about your family — the persistent, curated pages Memu maintains alongside its database.

## Structure

\`\`\`
spaces/<family_id>/
├── persons/        # one .md per person
├── routines/       # one .md per routine
├── households/     # household-level concerns (the car, the garden)
├── commitments/    # ongoing or upcoming commitments
├── documents/      # extracted documents (MOTs, passports, letters)
├── _log.md         # append-only audit log of every write
└── README.md       # this file
\`\`\`

Every .md file has YAML frontmatter (id, name, category, domains, people,
visibility, description, confidence, last_updated, source_references, tags)
and a markdown body. Wikilinks in the body — \`[[robin]]\`, \`[[school-run]]\` —
follow Obsidian conventions.

## How to read it

- **In Obsidian:** open this directory as a vault. Wikilinks form a graph view.
- **In a text editor:** every file is plain markdown.
- **In the mobile app:** the Spaces tab renders the database mirror.
- **In git:** \`git log\` shows the full history of synthesis updates,
  attributed to the person (or skill) that triggered each change.

## Backups & exports

This directory is git-versioned for free history. The complete archive
(including \`.git/\`) can be exported via \`POST /api/spaces/snapshot\` from
Settings, or as part of the full Article 20 export.

— Generated by Memu. Do not delete.
`;

async function ensureReadme(familyId: string, force = false): Promise<void> {
  const target = path.join(familyDir(familyId), 'README.md');
  if (!force) {
    try {
      await fs.access(target);
      return;
    } catch { /* fall through to write */ }
  }
  await fs.writeFile(target, README_BODY, 'utf8');
  try {
    execFileSync('git', ['add', '--', 'README.md'], { cwd: familyDir(familyId), stdio: 'ignore' });
    execFileSync(
      'git',
      ['commit', '-q', '-m', 'Initialise spaces directory', '--author', 'Memu <memu@localhost>'],
      { cwd: familyDir(familyId), stdio: 'ignore' },
    );
  } catch (err) {
    const msg = (err as Error).message ?? '';
    if (!/nothing to commit/i.test(msg)) {
      console.warn('[SPACES] README commit non-fatal:', msg);
    }
  }
}

export interface SpaceWriteInput {
  familyId: string;
  category: SpaceCategory;
  name: string;
  bodyMarkdown: string;
  description?: string;
  domains?: SpaceDomain[];
  people?: string[];
  visibility?: Visibility;
  confidence?: number;
  sourceReferences?: string[];
  tags?: string[];
  slug?: string;
  actorProfileId?: string;
  /**
   * URI of an existing top-level Space to nest this one under. Pass
   * null to explicitly un-parent. Omit to leave parent unchanged on
   * update; on insert, omitting means top-level.
   *
   * The caller is responsible for running validateParentRelationship
   * BEFORE calling upsertSpace — upsertSpace itself does not validate
   * because the v1 callers (autolearn, synthesis) write thousands of
   * times per day and don't touch parents. Only the v2 endpoints
   * that mutate parent_space_uri need to validate.
   */
  parentSpaceUri?: string | null;
  /**
   * Phase 4 of Build Spec 1 — optional project membership.
   *
   * Same shape as parentSpaceUri:
   *   - undefined → leave unchanged on update; default NULL on insert
   *   - null      → explicitly un-project (collective-level Space)
   *   - string    → set/replace; MUST be a project in the same
   *                 collective (enforced inside upsertSpace — RLS
   *                 hides cross-collective projects, so a lookup
   *                 that returns zero rows is the rejection signal)
   *
   * Unlike parent validation, upsertSpace DOES validate this inline
   * because cross-collective project assignment is the spec's hard
   * invariant and silently dropping the assignment would be worse
   * than a thrown error.
   */
  projectId?: string | null;
}

/**
 * Phase 4 — thrown when upsertSpace receives a projectId that either
 * doesn't exist or belongs to a different collective (RLS makes those
 * indistinguishable from this side; either way the assignment is
 * illegal). Carries the offending projectId + the Space's collective
 * scope so the API layer can surface a useful 422.
 */
export class SpaceProjectError extends Error {
  readonly reason: 'project_not_in_collective';
  readonly projectId: string;
  readonly collectiveId: string;
  constructor(projectId: string, collectiveId: string) {
    super(`Project ${projectId} is not in collective ${collectiveId}; cross-collective project assignment is forbidden.`);
    this.name = 'SpaceProjectError';
    this.reason = 'project_not_in_collective';
    this.projectId = projectId;
    this.collectiveId = collectiveId;
  }
}

/**
 * Build Spec 2 Phase R1 — thrown when a Space write tries to use a
 * category that's not in the owning workspace's type's category set
 * (e.g. `theme` in a family workspace, `routine` in a research
 * workspace). The DB CHECK constraint only enforces the UNION of all
 * sets — this error is the type-aware rule. Carries the offending
 * category + workspace type so the API layer can surface a 422 that
 * names both ("`theme` is not a valid category for a `family`
 * workspace").
 */
export class SpaceCategoryError extends Error {
  readonly reason: 'category_not_in_workspace_type';
  readonly category: string;
  readonly workspaceType: string;
  constructor(category: string, workspaceType: string) {
    super(`Category "${category}" is not valid for a ${workspaceType} workspace. Adjust the workspace type or the Space category.`);
    this.name = 'SpaceCategoryError';
    this.reason = 'category_not_in_workspace_type';
    this.category = category;
    this.workspaceType = workspaceType;
  }
}

export interface ParentValidationResult {
  ok: boolean;
  /** Discriminated reason on failure — usable by the API layer to map to 422 + message. */
  reason?:
    | 'parent_not_found'
    | 'parent_cross_family'
    | 'parent_is_self'
    | 'parent_has_parent'
    | 'invalid_uri';
  message?: string;
}

/**
 * Validate that `parentUri` is a legal parent for a Space in `familyId`.
 *
 * - parent must exist
 * - parent must belong to the same family
 * - parent must not be the Space itself (when `selfUri` provided)
 * - parent must not itself have a parent (two-level constraint)
 *
 * Pass `parentUri = null` to skip validation entirely (un-parenting is
 * always legal). Pass an empty/undefined parentUri only via the
 * orchestrating endpoint — the validator treats it as invalid because
 * "explicitly unset" should be `null`, not absent.
 */
export async function validateParentRelationship(
  familyId: string,
  parentUri: string | null,
  selfUri?: string,
): Promise<ParentValidationResult> {
  if (parentUri === null) return { ok: true };
  if (typeof parentUri !== 'string' || parentUri.trim() === '') {
    return { ok: false, reason: 'invalid_uri', message: 'parentSpaceUri must be a non-empty string or null' };
  }
  if (selfUri && parentUri === selfUri) {
    return { ok: false, reason: 'parent_is_self', message: 'A Space cannot be its own parent.' };
  }
  const res = await db.query<{ family_id: string; parent_space_uri: string | null }>(
    `SELECT family_id, parent_space_uri FROM synthesis_pages WHERE uri = $1 LIMIT 1`,
    [parentUri],
  );
  if (!res.rows[0]) {
    return { ok: false, reason: 'parent_not_found', message: `No Space found at ${parentUri}.` };
  }
  if (res.rows[0].family_id !== familyId) {
    return { ok: false, reason: 'parent_cross_family', message: 'Parent Space belongs to a different family.' };
  }
  if (res.rows[0].parent_space_uri) {
    return {
      ok: false,
      reason: 'parent_has_parent',
      message:
        'Two-level limit: the chosen parent already has a parent of its own. Pick a top-level Space, or its parent, instead.',
    };
  }
  return { ok: true };
}

/**
 * Upsert a Space, keyed on (family_id, category, slug). If a row
 * already exists at that key, this becomes an update (keeps the URI).
 * Otherwise a new row is minted with a freshly-generated URI.
 */
export async function upsertSpace(input: SpaceWriteInput): Promise<Space> {
  const slug = input.slug ?? slugify(input.name);
  // Pre-Beta Stream 1 — db.transaction picks up the active collective
  // context. Caller must be inside enterCollectiveContext (typical:
  // they're inside a Fastify request that went through requireCollective).
  const space = await db.transaction(async (client) => {
    // One lookup of the owning workspace's type, used for two
    // type-aware concerns: Phase Z Story Z.2 (passage-id assignment
    // for research bodies) and Phase R1 (category set validation —
    // the DB CHECK enforces only the UNION; the type-aware rule
    // lives here). The lookup is on the collectives table (Tier-C,
    // no RLS) — safe to read inside the tenant tx.
    const wsTypeRes = await client.query<{ type: string }>(
      `SELECT type FROM collectives WHERE id = $1 LIMIT 1`,
      [input.familyId],
    );
    const workspaceType = wsTypeRes.rows[0]?.type ?? 'family';

    // R1 — reject a category that's not in this workspace type's set.
    // The error names both halves so the log line is self-explanatory.
    if (!isCategoryAllowedForType(input.category, workspaceType)) {
      throw new SpaceCategoryError(input.category, workspaceType);
    }

    // Z.2 — research workspaces get pid-augmented bodies; others pass
    // through unchanged so family Space bodies are byte-identical to
    // pre-Phase-Z.
    const bodyMarkdownForWrite = workspaceType === 'research'
      ? assignPassageIds(input.bodyMarkdown)
      : input.bodyMarkdown;

    let existingId: string | null = null;
    let existingUri: string | null = null;
    const existing = await client.query<{ id: string; uri: string }>(
      `SELECT id, uri FROM synthesis_pages
        WHERE family_id = $1 AND category = $2 AND slug = $3
        LIMIT 1`,
      [input.familyId, input.category, slug],
    );
    if (existing.rows[0]) {
      existingId = existing.rows[0].id;
      existingUri = existing.rows[0].uri;
    }

    const id = existingId ?? crypto.randomUUID();
    const uri = existingUri ?? buildSpaceUri(input.familyId, input.category, id);
    const visibilityStored = Array.isArray(input.visibility)
      ? JSON.stringify(input.visibility)
      : (input.visibility ?? 'family');

    const profileId = input.actorProfileId ?? input.familyId;

    // parent_space_uri write semantics (Spaces Canvas v2):
    //   - input.parentSpaceUri === undefined → leave column unchanged
    //     on update (omit from SET), default to NULL on insert
    //   - input.parentSpaceUri === null     → explicitly un-parent
    //   - input.parentSpaceUri = string     → set/replace
    //
    // We thread this through with COALESCE-style logic on update to
    // avoid clobbering a previously-set parent when v1 callers
    // (autolearn / synthesis) upsert a body without thinking about
    // parents.
    const parentInsertValue = input.parentSpaceUri === undefined ? null : input.parentSpaceUri;
    const parentUpdateMode = input.parentSpaceUri === undefined ? 'preserve' : 'replace';

    const updateClauseParent = parentUpdateMode === 'replace'
      ? 'parent_space_uri = EXCLUDED.parent_space_uri,'
      : ''; // preserve — omit from the SET list

    // Phase 4: project_id mirrors parent_space_uri's shape — undefined
    // preserves on update / NULL on insert; null explicitly un-projects;
    // a string must reference a project in the SAME collective.
    const projectInsertValue = input.projectId === undefined ? null : input.projectId;
    const projectUpdateMode = input.projectId === undefined ? 'preserve' : 'replace';
    const updateClauseProject = projectUpdateMode === 'replace'
      ? 'project_id = EXCLUDED.project_id,'
      : '';

    // Validate project_id when explicitly set to a non-null string. RLS
    // scopes the SELECT to the active collective, so a project in a
    // different collective is indistinguishable from a non-existent
    // project from this side — both are rejected with the same error.
    if (typeof input.projectId === 'string' && input.projectId.length > 0) {
      const projCheck = await client.query<{ id: string }>(
        `SELECT id FROM projects WHERE id = $1 LIMIT 1`,
        [input.projectId],
      );
      if (projCheck.rows.length === 0) {
        throw new SpaceProjectError(input.projectId, input.familyId);
      }
    }

    // Phase 1: embed the Space body on every write. Same text shape as
    // backfillEmbeddings.ts (title + description + body) so backfilled
    // and live-written embeddings live in the same semantic space.
    // Phase Z Z.2 — embed the augmented body (with pid comments) so
    // search recall over research Spaces is consistent regardless of
    // when the embedding was generated. The 10–30 chars of comment
    // noise per block is below the noise floor of MiniLM-L6's 384-dim
    // representation.
    const embeddingText = [input.name, input.description ?? '', bodyMarkdownForWrite]
      .map(s => (s ?? '').trim())
      .filter(Boolean)
      .join('\n\n');
    const embeddingVec = embeddingText ? await embedText(embeddingText) : null;
    const embeddingStr = embeddingVec ? `[${embeddingVec.join(',')}]` : null;

    await client.query(
      `INSERT INTO synthesis_pages (
         id, profile_id, family_id, uri, slug, category, title, body_markdown,
         description, domains, people, visibility, confidence,
         source_references, tags, parent_space_uri, embedding, project_id, last_updated_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::vector,$18, NOW())
       ON CONFLICT (id) DO UPDATE SET
         title = EXCLUDED.title,
         body_markdown = EXCLUDED.body_markdown,
         description = EXCLUDED.description,
         domains = EXCLUDED.domains,
         people = EXCLUDED.people,
         visibility = EXCLUDED.visibility,
         confidence = EXCLUDED.confidence,
         source_references = EXCLUDED.source_references,
         tags = EXCLUDED.tags,
         embedding = EXCLUDED.embedding,
         ${updateClauseProject}
         ${updateClauseParent}
         last_updated_at = NOW()`,
      [
        id,
        profileId,
        input.familyId,
        uri,
        slug,
        input.category,
        input.name,
        bodyMarkdownForWrite,
        input.description ?? '',
        input.domains ?? [],
        input.people ?? [],
        visibilityStored,
        input.confidence ?? 0.5,
        input.sourceReferences ?? [],
        input.tags ?? [],
        parentInsertValue,
        embeddingStr,
        projectInsertValue,
      ],
    );

    // Phase 6 of Build Spec 1 — persist wikilink edges from the body.
    // Runs after the synthesis_pages write so the source Space is
    // guaranteed to exist, and inside the same transaction so a
    // failure here rolls back the Space write too (consistent state
    // is more important than partial graph coverage). RLS scopes the
    // target resolution to the active collective — cross-collective
    // [[targets]] silently resolve to nothing.
    await persistWikilinkEdges(client, uri, bodyMarkdownForWrite);

    await client.query(
      `INSERT INTO spaces_log (family_id, space_uri, event, summary, actor_profile_id)
       VALUES ($1, $2, $3, $4, $5)`,
      [
        input.familyId,
        uri,
        existingId ? 'updated' : 'created',
        `${existingId ? 'Updated' : 'Created'} ${input.category} "${input.name}"`,
        input.actorProfileId ?? null,
      ],
    );

    // Resolve effective parent for the in-memory Space we hand back —
    // either the just-written value (replace mode) or the pre-existing
    // value (preserve mode). For inserts (existingId === null), the
    // parent is whatever we wrote.
    let effectiveParent: string | null;
    if (existingId === null || parentUpdateMode === 'replace') {
      effectiveParent = parentInsertValue;
    } else {
      const r = await client.query<{ parent_space_uri: string | null }>(
        `SELECT parent_space_uri FROM synthesis_pages WHERE id = $1`,
        [id],
      );
      effectiveParent = r.rows[0]?.parent_space_uri ?? null;
    }

    const built: Space = {
      uri,
      id,
      familyId: input.familyId,
      category: input.category,
      slug,
      name: input.name,
      description: input.description ?? '',
      domains: input.domains ?? [],
      people: input.people ?? [],
      visibility: input.visibility ?? 'family',
      confidence: input.confidence ?? 0.5,
      sourceReferences: input.sourceReferences ?? [],
      tags: input.tags ?? [],
      bodyMarkdown: bodyMarkdownForWrite,
      lastUpdated: new Date(),
      parentSpaceUri: effectiveParent,
    };

    // Stash existingId on the returned object so the caller can decide
    // whether the FS write event is "created" or "updated". (We can't
    // call writeToDisk inside the transaction — FS ops aren't
    // transactional and a rollback wouldn't undo them.)
    return { space: built, wasCreate: existingId === null };
  });

  await writeToDisk(space.space, space.wasCreate ? 'created' : 'updated', input.actorProfileId);
  return space.space;
}

function renderFrontmatter(space: Space): string {
  const fm: Record<string, unknown> = {
    id: space.uri,
    name: space.name,
    category: space.category,
    domains: space.domains,
    people: space.people,
    visibility: space.visibility,
    description: space.description,
    confidence: space.confidence,
    last_updated: space.lastUpdated.toISOString(),
    source_references: space.sourceReferences,
    tags: space.tags,
  };
  // Only emit parent_space_uri when there's a parent — keeps top-level
  // .md files clean and stops legacy diff churn.
  if (space.parentSpaceUri) fm.parent_space_uri = space.parentSpaceUri;
  return matter.stringify(space.bodyMarkdown.endsWith('\n') ? space.bodyMarkdown : `${space.bodyMarkdown}\n`, fm);
}

async function writeToDisk(space: Space, event: 'created' | 'updated', actorProfileId?: string): Promise<void> {
  await ensureFamilyRepo(space.familyId);
  const target = filePath(space.familyId, space.category, space.slug);
  await fs.mkdir(path.dirname(target), { recursive: true });
  await fs.writeFile(target, renderFrontmatter(space), 'utf8');

  const logLine = `- ${space.lastUpdated.toISOString()} · ${event} · [[${space.slug}]] (${space.category})\n`;
  await fs.appendFile(logPath(space.familyId), logLine, 'utf8');

  const relFile = path.relative(familyDir(space.familyId), target);
  const relLog = path.relative(familyDir(space.familyId), logPath(space.familyId));
  const actor = await resolveActor(actorProfileId);
  const verb = event === 'created' ? 'Created' : 'Updated';
  const message = `${verb} ${space.category}/${space.slug}.md\n\n${space.name}\nVisibility: ${Array.isArray(space.visibility) ? 'explicit' : space.visibility}`;
  try {
    execFileSync('git', ['add', '--', relFile, relLog], { cwd: familyDir(space.familyId), stdio: 'ignore' });
    execFileSync(
      'git',
      ['commit', '-q', '-m', message, '--author', `${actor.name} <${actor.email}>`],
      { cwd: familyDir(space.familyId), stdio: 'ignore' },
    );
  } catch (err) {
    const msg = (err as Error).message ?? '';
    if (!/nothing to commit/i.test(msg)) {
      console.warn('[SPACES] git commit non-fatal:', msg);
    }
  }
}

interface SpaceRow {
  id: string;
  family_id: string;
  uri: string;
  slug: string;
  category: SpaceCategory;
  title: string;
  body_markdown: string;
  description: string;
  domains: string[];
  people: string[];
  visibility: string;
  confidence: string;
  source_references: string[];
  tags: string[];
  last_updated_at: Date;
  parent_space_uri: string | null;
}

function rowToSpace(row: SpaceRow): Space {
  let visibility: Visibility;
  if (row.visibility.startsWith('[')) {
    try {
      visibility = JSON.parse(row.visibility) as string[];
    } catch {
      visibility = 'family';
    }
  } else {
    visibility = row.visibility as Visibility;
  }
  return {
    uri: row.uri,
    id: row.id,
    familyId: row.family_id,
    category: row.category,
    slug: row.slug,
    name: row.title,
    description: row.description,
    domains: row.domains as SpaceDomain[],
    people: row.people,
    visibility,
    confidence: Number(row.confidence),
    sourceReferences: row.source_references,
    tags: row.tags,
    bodyMarkdown: row.body_markdown,
    lastUpdated: row.last_updated_at,
    parentSpaceUri: row.parent_space_uri,
  };
}

const SPACE_ROW_COLUMNS = `id, family_id, uri, slug, category, title, body_markdown,
       description, domains, people, visibility, confidence,
       source_references, tags, last_updated_at, parent_space_uri`;

export async function findSpaceByUri(uri: string): Promise<Space | null> {
  const res = await db.query<SpaceRow>(
    `SELECT ${SPACE_ROW_COLUMNS} FROM synthesis_pages WHERE uri = $1`,
    [uri],
  );
  return res.rows[0] ? rowToSpace(res.rows[0]) : null;
}

export async function findSpaceBySlug(familyId: string, category: SpaceCategory, slug: string): Promise<Space | null> {
  const res = await db.query<SpaceRow>(
    `SELECT ${SPACE_ROW_COLUMNS} FROM synthesis_pages
      WHERE family_id = $1 AND category = $2 AND slug = $3`,
    [familyId, category, slug],
  );
  return res.rows[0] ? rowToSpace(res.rows[0]) : null;
}

export async function listSpaces(familyId: string): Promise<Space[]> {
  const res = await db.query<SpaceRow>(
    `SELECT ${SPACE_ROW_COLUMNS} FROM synthesis_pages WHERE family_id = $1
      ORDER BY last_updated_at DESC`,
    [familyId],
  );
  return res.rows.map(rowToSpace);
}

/**
 * Return the count of children for each Space URI in `parentUris`.
 * Used by the graph endpoint to surface childCount per node and by
 * findSpaces (Claude tool) to tell Claude whether a match is itself
 * a container.
 */
export async function countChildrenForParents(
  familyId: string,
  parentUris: string[],
): Promise<Map<string, number>> {
  const result = new Map<string, number>();
  if (parentUris.length === 0) return result;
  const res = await db.query<{ parent_space_uri: string; n: string }>(
    `SELECT parent_space_uri, COUNT(*)::text AS n
       FROM synthesis_pages
      WHERE family_id = $1 AND parent_space_uri = ANY($2::text[])
      GROUP BY parent_space_uri`,
    [familyId, parentUris],
  );
  for (const row of res.rows) result.set(row.parent_space_uri, Number(row.n));
  return result;
}

/**
 * List the children of a parent Space. Order: most-recently-updated
 * first, matching listSpaces. Visibility filtering is the caller's
 * responsibility — store.ts is the data layer.
 */
export async function listChildren(parentUri: string): Promise<Space[]> {
  const res = await db.query<SpaceRow>(
    `SELECT ${SPACE_ROW_COLUMNS} FROM synthesis_pages
      WHERE parent_space_uri = $1
      ORDER BY last_updated_at DESC`,
    [parentUri],
  );
  return res.rows.map(rowToSpace);
}

/**
 * Delete a Space. Removes the DB row, the on-disk markdown file, and
 * commits the deletion to the family's git repo so blame still shows
 * who removed it. Returns true if a row was deleted, false if the slug
 * was already gone (idempotent — callers don't need to pre-check).
 */
export async function deleteSpace(
  familyId: string,
  category: SpaceCategory,
  slug: string,
  actorProfileId?: string,
): Promise<boolean> {
  // Pre-Beta Stream 1 — db.transaction picks up the active collective
  // context (caller is inside enterCollectiveContext via requireCollective
  // or an explicit cron entry). RLS gates the SELECT so a cross-collective
  // (familyId, category, slug) tuple just returns no row.
  const deleted = await db.transaction(async (client) => {
    const existing = await client.query<{ uri: string; title: string }>(
      `SELECT uri, title FROM synthesis_pages
        WHERE family_id = $1 AND category = $2 AND slug = $3
        LIMIT 1`,
      [familyId, category, slug],
    );
    if (!existing.rows[0]) return null;
    const removedUri = existing.rows[0].uri;
    const removedTitle = existing.rows[0].title;

    // Orphan children before deleting the parent — sub-Spaces are
    // independent content; the parent relationship was contextual,
    // not constitutive. The orphaned children are noted in spaces_log
    // so audit history shows the reason their parent went away.
    const orphaned = await client.query<{ uri: string }>(
      `UPDATE synthesis_pages SET parent_space_uri = NULL
        WHERE family_id = $1 AND parent_space_uri = $2
        RETURNING uri`,
      [familyId, removedUri],
    );
    if (orphaned.rows.length > 0) {
      const orphanLog = orphaned.rows.map(r => r.uri).join(', ');
      await client.query(
        `INSERT INTO spaces_log (family_id, space_uri, event, summary, actor_profile_id)
         VALUES ($1, $2, 'updated', $3, $4)`,
        [familyId, removedUri, `Orphaned ${orphaned.rows.length} child Space(s) — parent deleted: ${orphanLog}`, actorProfileId ?? null],
      );
    }

    await client.query(
      `DELETE FROM synthesis_pages WHERE family_id = $1 AND category = $2 AND slug = $3`,
      [familyId, category, slug],
    );
    await client.query(
      `INSERT INTO spaces_log (family_id, space_uri, event, summary, actor_profile_id)
       VALUES ($1, $2, 'deleted', $3, $4)`,
      [familyId, removedUri, `Deleted ${category} "${removedTitle}"`, actorProfileId ?? null],
    );
    return { removedUri, removedTitle };
  });

  if (!deleted) return false;

  // Best-effort filesystem cleanup. The DB is the source of truth; if
  // the file is missing the delete still succeeded.
  try {
    await ensureFamilyRepo(familyId);
    const target = filePath(familyId, category, slug);
    try { await fs.unlink(target); } catch { /* already gone */ }
    const logLine = `- ${new Date().toISOString()} · deleted · [[${slug}]] (${category})\n`;
    await fs.appendFile(logPath(familyId), logLine, 'utf8');
    const relFile = path.relative(familyDir(familyId), target);
    const relLog = path.relative(familyDir(familyId), logPath(familyId));
    const actor = await resolveActor(actorProfileId);
    try {
      execFileSync('git', ['add', '--', relFile, relLog], { cwd: familyDir(familyId), stdio: 'ignore' });
      execFileSync(
        'git',
        ['commit', '-q', '-m', `Deleted ${category}/${slug}.md`, '--author', `${actor.name} <${actor.email}>`],
        { cwd: familyDir(familyId), stdio: 'ignore' },
      );
    } catch (err) {
      const msg = (err as Error).message ?? '';
      if (!/nothing to commit/i.test(msg)) {
        console.warn('[SPACES] git delete commit non-fatal:', msg);
      }
    }
  } catch (err) {
    console.warn('[SPACES] filesystem cleanup non-fatal:', (err as Error).message);
  }

  return true;
}

/**
 * Re-derive the on-disk spaces tree from the database. Used after
 * migrations, disaster recovery, or manual surgery. Idempotent.
 */
export async function rebuildOnDisk(familyId: string): Promise<number> {
  const spaces = await listSpaces(familyId);
  await ensureFamilyRepo(familyId);
  for (const space of spaces) {
    await writeToDisk(space, 'updated', familyId);
  }
  return spaces.length;
}
